# Generated by Django 6.0.4 on 2026-04-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
