# Generated by Django 6.0.4 on 2026-04-19 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cars',
            new_name='Car',
        ),
    ]
